### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by janmarthedal** [DirkToewe/ndjs#1]
I just stumpled upon this library and it looks quite mature and capable.

It does not seem to be published to the public npm registry, however. Any intention of doing so?

I can see there is a .npmignore file, so I guess it has been considered?

**Comment by DirkToewe** [comment]
Hi @janmarthedal,
Thank You for the interest in the project.

You guessed correctly. Publishing to NPM was considered from the start. NDJS is my first JavaScript project. In the beginning I was happy to even get building (Babel+Webpack) and testing (Karma+Jasmine) to work. Then it took me a long time to study, understand and implement all the linear algebra decompositions. All the while I was dodging the topic of publishing to npm, partly because I was scared of it. But now I have no more excuses. So I will look into it next :)

**Comment by DirkToewe** [comment]
The first release is now on NPM under the name `nd4js` (ndjs was taken, so the library is going to be renamed):
```
npm i nd4js
```
Currently I can only test under Linux using the latest Chrome and Firefox. The next step is going to be setting up a CI test service covering multiple OS and browser configurations, I guess...

Please let me know if You experience any issues.
