### ISSUE TITLE
lstsq produces incorrect result

### ISSUE THREAD

**Issue by janmarthedal** [DirkToewe/ndjs#4]
The following code snippet illustrates an incorrect result for the `la.lstsq` method.

The least squares solution should obviously be `[[1], [1]]`, and not `[[0], [0]]`.

```javascript
const nd = require('nd4js');

const a = nd.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5],
    [1, 6]
]);

const b = nd.array([
    [2],
    [3],
    [4],
    [5],
    [6],
    [7]
]);

const x = nd.la.lstsq(a, b);

console.log(x);
```

**Comment by DirkToewe** [comment]
Thank You for spotting that error.

The issue seems to happen if `a.dtype` is `'int32'`. As a temporary workaround, You can cast a to `float32` or `float64` explicitly, e.g. via `nd.array('float64', [...])` or `a.mapElems('float64')`

A fixed version will be published as soon as I get to it which will either be tonight or on Thursday.

**Comment by DirkToewe** [comment]
`r1.0.1` is on NPM and hopefully is fixes the issue. If You still experience the issue or any other issue, please feel free reopen this issue or open a new one. For every bug being found I'm grateful :)
