### ISSUE TITLE
BigNumbers

### ISSUE THREAD

**Issue by iammadab** [DirkToewe/ndjs#5]
Does this work with bignumbers?

**Comment by DirkToewe** [comment]
Only as small part of `nd4js` supports custom data types:
  * `opt` (optimization) submodule does not support custom data types
  * `la` (linear algebra) submodule does not support custom data types (_except for matmul_)
  * N-ary operations and factory method should be data type agnostic and should work fine

Below, You will find a few code snippets that show how to use `nd4js` with `bignumber.js`. I have also created a [RunKit Notebook here](https://runkit.com/embed/37s7ve5gxrjb) so You can play around with the code more easily. Hope this helps.

### Factory Methods
All the factory methods _should_ work:
```js
const nd = require("nd4js"),
  BigNum = require('bignumber.js');

const A = nd.tabulate([3,3], (i,j) => BigNum(11+10*i+j));
console.log('A:\n' + A);

const B = nd.array(
  [[BigNum(1), BigNum(2), BigNum(3)],
   [BigNum(4), BigNum(5), BigNum(6)],
   [BigNum(7), BigNum(8), BigNum(9)]]
);
console.log('B:\n' + B);
```
### N-ary Operations
Unary, Binary, Ternary, ... operations all _should_ work with any data type:
```js
console.log('2*A=\n' + A.mapElems(a => a.times(2)) );

console.log('A+B=\n' + nd.zip_elems([A,B], (a,b) => a.plus(b)) );
```
### Matmul
In order to use matrix multiplication, You will have to override the default scalar addition and multiplication in `nd.math`:
```js
const default_add = nd.math.add,
      default_mul = nd.math.mul;
// override addition
nd.math.add = (x,y) => {
  if( x instanceof BigNum ||
      y instanceof BigNum ) {
    if( !(x instanceof BigNum) ) x = BigNum(x);
    return x.plus(y);
  }
  else
    return default_add(x,y);
}
// override multiplication
nd.math.mul = (x,y) => {
  if( x instanceof BigNum ||
      y instanceof BigNum ) {
    if( !(x instanceof BigNum) ) x = BigNum(x);
    return x.times(y);
  }
  else
    return default_mul(x,y);
}

console.log('AB=\n' + nd.la.matmul2(A,B));
```

**Comment by iammadab** [comment]
Great, I can work with this. This helps. Thanks.

**Comment by DirkToewe** [comment]
Happy to be of help. If You have any more questions, experience any issues or have any feature requests, feel free to (re)open this issue or a new one.
